### PR TITLE
Creating a marathon-template executable

### PR DESCRIPTION
**Pull request by ashwanthkumar**
1. Moving things from scripts to app, makes it look a little cleaner
2. Extracted the marathon main out to marathon-template executable

### CODE REVIEW

**Comment by brewkode** [comment]
Marathon main hasn't been moved out yet.

**Comment by brewkode** [comment]
Would've liked a separate bin script that calls the py script. Python script without the extension feels incomplete :)

**Comment by ashwanthkumar** [comment]
Okay, I'll create a shell script instead then.

**Comment by ashwanthkumar** [comment]
BTW when you say marathon main hasn't moved out, you mean the fact that `if __name__ == '__main__':` section is still in the marathon-template ?

**Pull request merged**
